// Generated by CoffeeScript 1.12.4
(function() {
  var say_hi;

  say_hi = function() {
    return console.log('Hello!!!');
  };

  $(function() {
    return $("#btn1").on('click', (function(_this) {
      return function() {
        return console.log('click');
      };
    })(this));
  });

  window["say_hi"] = say_hi;

}).call(this);
